import streamlit as st
import json
import io
from datetime import datetime
from fpdf import FPDF
from extractor import analyze_text, PARAMETERS

# -----------------------------------------------
# Load translations
# -----------------------------------------------

def load_translations(lang: str) -> dict:
    with open(f"locales/{lang}.json", encoding="utf-8") as f:
        return json.load(f)

# -----------------------------------------------
# PDF Export
# -----------------------------------------------

def generate_pdf(findings: list, user_input: str, tr: dict, lang: str) -> bytes:
    pdf = FPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    # Header
    pdf.set_font("Helvetica", "B", 16)
    pdf.set_fill_color(240, 248, 255)
    pdf.cell(0, 12, "Clinical Lab Results Report", ln=True, align="C", fill=True)
    pdf.set_font("Helvetica", size=9)
    pdf.cell(0, 6, f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}", ln=True, align="C")
    pdf.ln(4)

    # Disclaimer
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(150, 0, 0)
    pdf.multi_cell(0, 5, "DISCLAIMER: This report is for educational purposes only and does not constitute medical advice.")
    pdf.set_text_color(0, 0, 0)
    pdf.ln(4)

    # Input text
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 8, "Input:", ln=True)
    pdf.set_font("Helvetica", size=9)
    pdf.set_fill_color(248, 248, 248)
    pdf.multi_cell(0, 5, user_input[:300], fill=True)
    pdf.ln(4)

    # Summary
    has_abnormal = any(f["status_key"] != "normal" for f in findings)
    pdf.set_font("Helvetica", "B", 12)
    if has_abnormal:
        pdf.set_text_color(180, 0, 0)
        pdf.cell(0, 8, "Result: Out-of-range values detected", ln=True)
    else:
        pdf.set_text_color(0, 120, 0)
        pdf.cell(0, 8, "Result: All values within normal range", ln=True)
    pdf.set_text_color(0, 0, 0)
    pdf.ln(3)

    # Table header
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_fill_color(220, 235, 255)
    col_w = [45, 25, 15, 50, 55]
    headers = ["Parameter", "Value", "Unit", "Status", "Reference"]
    for i, h in enumerate(headers):
        pdf.cell(col_w[i], 7, h, border=1, fill=True)
    pdf.ln()

    # Table rows
    pdf.set_font("Helvetica", size=8)
    for f in findings:
        is_abnormal = f["status_key"] != "normal"
        if is_abnormal:
            pdf.set_fill_color(255, 240, 240)
        else:
            pdf.set_fill_color(240, 255, 240)

        op = f.get("operator") or ""
        val_str = f"{op}{f['value']}"
        status_clean = f["status"].replace("✅", "").replace("⚠️", "!").replace("🔶", "~").replace("🔴", "!!").strip()
        ref_clean = f["reference"][:50]

        pdf.cell(col_w[0], 6, f["name"][:22], border=1, fill=True)
        pdf.cell(col_w[1], 6, val_str, border=1, fill=True)
        pdf.cell(col_w[2], 6, f["unit"][:10], border=1, fill=True)
        pdf.cell(col_w[3], 6, status_clean[:28], border=1, fill=True)
        pdf.cell(col_w[4], 6, ref_clean, border=1, fill=True)
        pdf.ln()

    # Recommendations
    abnormal = [f for f in findings if f["status_key"] != "normal" and f["advice"]]
    if abnormal:
        pdf.ln(5)
        pdf.set_font("Helvetica", "B", 11)
        pdf.cell(0, 8, "Recommendations:", ln=True)
        pdf.set_font("Helvetica", size=9)
        for f in abnormal:
            pdf.set_font("Helvetica", "B", 9)
            pdf.cell(0, 6, f"  {f['name']}:", ln=True)
            pdf.set_font("Helvetica", size=8)
            pdf.multi_cell(0, 5, f"  {f['advice']}")
            pdf.ln(2)

    pdf.ln(5)
    pdf.set_font("Helvetica", "I", 7)
    pdf.set_text_color(120, 120, 120)
    pdf.cell(0, 5, "This report was generated by Clinical Lab Results Interpreter — educational use only.", ln=True, align="C")

    return bytes(pdf.output())

# -----------------------------------------------
# UI Setup
# -----------------------------------------------

st.set_page_config(page_title="Clinical Lab Results Interpreter", layout="centered")

SAMPLES = {
    "en": "Ferritin 8 ng/mL, Hemoglobin 10.2 g/dL, Glucose 140 mg/dL, CRP 45 mg/L, TSH 0.2 mIU/L",
    "fr": "Ferritine 8 ng/mL, Hémoglobine 10.2 g/dL, Glycémie 140 mg/dL, CRP 45 mg/L, TSH 0.2 mIU/L",
    "ar": "Ferritin 8 ng/mL, Hemoglobin 10.2 g/dL, Glucose 140 mg/dL, CRP 45 mg/L, TSH 0.2 mIU/L",
}

# Language selector
with st.sidebar:
    lang = st.selectbox(
        "🌐 Language",
        ["en", "fr", "ar"],
        format_func=lambda x: {"en": "🇬🇧 English", "fr": "🇫🇷 Français", "ar": "🇸🇦 العربية"}[x]
    )

tr = load_translations(lang)

# RTL for Arabic
if lang == "ar":
    st.markdown("""<style>
        .stApp, .stTextArea textarea, p, label { direction: rtl; text-align: right; }
    </style>""", unsafe_allow_html=True)

# Sidebar content
with st.sidebar:
    st.markdown("---")
    st.caption(f"📚 {len(PARAMETERS)} {tr['sidebar_params']}")
    with st.expander(tr["sidebar_how"]):
        st.markdown(tr["sidebar_how_text"])

# Main UI
st.title(tr["title"])
st.write(tr["subtitle"])
st.markdown(tr["disclaimer"])

col1, col2 = st.columns([3, 1])
with col1:
    st.markdown(f"**{tr['input_label']}**")
with col2:
    if st.button(tr["sample_btn"]):
        st.session_state["sample_text"] = SAMPLES[lang]

default_text = st.session_state.get("sample_text", "")
user_input = st.text_area(
    "", value=default_text, height=130,
    placeholder=tr["placeholder"],
    label_visibility="collapsed"
)

# -----------------------------------------------
# Analysis
# -----------------------------------------------

if st.button(tr["button"], type="primary"):
    if user_input.strip() == "":
        st.warning(tr["empty_warning"])
    else:
        findings = analyze_text(user_input, lang)

        if not findings:
            st.warning(tr["no_interp"])
        else:
            has_abnormal = any(f["status_key"] != "normal" for f in findings)
            if has_abnormal:
                st.error(tr["result_abnormal"])
            else:
                st.success(tr["result_normal"])

            # Detailed results
            st.subheader(tr["interp_title"])
            for f in findings:
                icon = "✅" if f["status_key"] == "normal" else "⚠️"
                op = f.get("operator") or ""
                with st.expander(f"{icon} {f['name']} — {op}{f['value']} {f['unit']}"):
                    st.markdown(f"**{f['status']}**")
                    st.caption(f"📐 {tr['ref_label']}: {f['reference']}")
                    if f["advice"]:
                        st.info(f"💡 {f['advice']}")

            # PDF Export
            st.markdown("---")
            pdf_bytes = generate_pdf(findings, user_input, tr, lang)
            st.download_button(
                label=tr["export_btn"],
                data=pdf_bytes,
                file_name=tr["export_filename"],
                mime="application/pdf"
            )
